API Auth Ingest/Consumption
514-labs/moose pull request #1648
Opened 2024-07-31 17:12 UTC by georgevanderson

Set the hashed values as environment variables to turn on auth
MOOSE_INGEST_API_KEY
MOOSE_CONSUMPTION_API_KEY

2024-07-31 17:56 UTC, phiSgr reviewed
just some code style stuff

2024-07-31 17:56 UTC, phiSgr commented on apps/framework-cli/src/cli/local_webserver.rs
> +            .map_err(Into::into);
looks like we don't need `.map_err(Into::into);`

2024-07-31 17:56 UTC, phiSgr commented on apps/framework-cli/src/cli/local_webserver.rs
> +    let bearer_token = match auth_header {
maybe use and_then?

https://doc.rust-lang.org/std/option/enum.Option.html#method.and_then

2024-07-31 17:56 UTC, phiSgr commented on apps/framework-cli/src/cli/local_webserver.rs
> +    match env::var(env_var) {
we can probably use `lazy_static` for that

2024-07-31 17:56 UTC, phiSgr commented on apps/framework-cli/src/cli/local_webserver.rs
> +        Ok(ingest_api_key) => match token {
`token.is_some_and`

2024-07-31 17:56 UTC, phiSgr commented on apps/framework-cli/src/cli/local_webserver.rs
> +            .map_err(Into::into);
i prefer `return Ok(...?);`

2024-07-31 18:26 UTC, callicles requested changes
Let's change the algorithm used for hashing

2024-07-31 18:26 UTC, callicles commented on apps/framework-cli/src/cli/local_webserver.rs
> +            Some(token) => hex_digest(Algorithm::SHA256, token.as_bytes()) == ingest_api_key,
We should not be using SHA-256 for this.

NIST recommends PBKDF2 - let's follow that recommendation with a constant time check on the output.

Ref: https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pbkdf2

https://github.com/RustCrypto/password-hashes/tree/master/pbkdf2

2024-08-02 15:46 UTC, callicles requested changes
Sorry - last change and then we will be good to go 😄 Security is hard

2024-08-02 15:46 UTC, callicles commented on apps/framework-cli/src/cli/routines/auth.rs
> +            return false;
If I am reading this correcly - you are doing an early return here - so not comparing byte. 

Doing constant time comparison is really hard - I would use a third-party to do that.

After some research I would use this: https://github.com/cesarb/constant_time_eq/tree/master

2024-08-02 16:29 UTC, callicles approved these changes
Nice work!

2024-08-02 16:44 UTC, merged